# Generated by Django 5.1.1 on 2025-01-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathquiz', '0003_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='この選択肢を登録してください。', verbose_name='不正解の選択肢')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_choices', to='mathquiz.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': '不正解の選択肢',
                'verbose_name_plural': '不正解の選択肢',
            },
        ),
    ]
