# Generated by Django 5.1.2 on 2024-12-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathquiz', '0002_alter_category_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='algebra_expression',
            field=models.TextField(blank=True, help_text='問題に関連する数式を記述します（例: Σ, √, lim）。', null=True, verbose_name='数式表現'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(help_text='この問題が属するカテゴリを選択してください。', on_delete=django.db.models.deletion.CASCADE, to='mathquiz.category', verbose_name='カテゴリ'),
        ),
    ]
