# Generated by Django 5.1.2 on 2025-02-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathquiz', '0004_incorrectchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='この問題が属するカテゴリを選択してください。', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathquiz.category', verbose_name='カテゴリ'),
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='この選択肢を登録してください。', verbose_name='正解の選択肢')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='mathquiz.question', verbose_name='正答')),
            ],
            options={
                'verbose_name': '正解の選択肢',
                'verbose_name_plural': '正解の選択肢',
            },
        ),
    ]
