"""
Django settings for quiz project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#y#(_(jarr_f23gu6=43%-b8f&-gtd@b91r00e2q9_0^q+et3v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 静的ファイルの詳細ログを有効にする
import logging
logging.basicConfig(level=logging.DEBUG)

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mathquiz',  # 作成したアプリケーション名が含まれているか確認
    'debug_toolbar',  # Django Debug Toolbar
]

# 🔹 セキュリティ関連の設定
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000"]  # ✅ CSRF エラー回避のため追加

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # ここに追加
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Django Debug Toolbarを127.0.0.1のみで動作
INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'quiz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "mathquiz/templates",  # 追加する！
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,  # デバッグオプションを追加
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }
]  # ← ここで TEMPLATES の二重定義を削除

WSGI_APPLICATION = 'quiz.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # 静的ファイルのURL

STATICFILES_DIRS = [
    BASE_DIR / 'mathquiz/static',  # プロジェクト内の静的ファイルディレクトリ
]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # ← コメントの崩れを修正

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # デフォルト

# セッションの有効期限設定（30分）
SESSION_COOKIE_AGE = 1800  

# ブラウザを閉じてもセッションが維持されるようにする
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  

# セッションの保存を強制
SESSION_SAVE_EVERY_REQUEST = True
